### PR TITLE
Re-exported OAuth

### PR DESCRIPTION
**Pull request by vsviridov**

### CODE REVIEW

**Comment by netpoetica** [comment]
Hi @vsviridov - thanks a ton for reporting and fixing this! I got a laugh out of some of the commits but for the sake of future people reading the history of this repo, do you think you could [rebase](https://git-scm.com/docs/git-rebase) into 1 individual commit and remove the commits that correct each other?

Thanks again!

**Comment by vsviridov** [comment]
Hmm, i tried doing interactive rebase with squash, but that still seems to keep the old commits in there... Not really sure about how to proceed. (Not much of a rebase user, unfortunately)

**Comment by netpoetica** [comment]
You might have more luck with a `--soft` reset, and then rewriting a commit message. Let me know if [this SO answer](http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git/5201642#5201642) helps you - it's got a couple of simple ways to accomplish this squash

**Comment by vsviridov** [comment]
Ok, I had to do a forced push, but that seemingly worked.

**Comment by netpoetica** [comment]
Thanks a ton! This is great :)

**Pull request merged**
